/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.simplex.desktop;

import br.com.simplexius.Simplex;
import br.com.simplexius.model.Fraction;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author jeansilva
 */
public class PrincipalPainel extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalPainel
     */
    public PrincipalPainel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtFuncaoObjetivo = new javax.swing.JTextField();
        cbFType = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMatrixRestricoes = new javax.swing.JTextArea();
        btnCalcular = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnExpTex = new javax.swing.JButton();
        btnExpPDF = new javax.swing.JButton();
        btnExpDoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simplex");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Função Objetivo"));
        jPanel2.setToolTipText("");

        cbFType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "min", "max" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFuncaoObjetivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFuncaoObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Matriz de Restrições"));
        jPanel1.setToolTipText("");

        txtMatrixRestricoes.setColumns(20);
        txtMatrixRestricoes.setRows(5);
        jScrollPane1.setViewportView(txtMatrixRestricoes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnExpTex.setIcon(new javax.swing.ImageIcon("/home/jeansilva/NetBeansProjects/SimplexDesktop/icons/tex3232.png")); // NOI18N
        btnExpTex.setFocusable(false);
        btnExpTex.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExpTex.setIconTextGap(0);
        btnExpTex.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnExpTex);

        btnExpPDF.setIcon(new javax.swing.ImageIcon("/home/jeansilva/NetBeansProjects/SimplexDesktop/icons/pdf_32.png")); // NOI18N
        btnExpPDF.setFocusable(false);
        btnExpPDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExpPDF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnExpPDF);

        btnExpDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/simplex/desktop/word32.png"))); // NOI18N
        btnExpDoc.setFocusable(false);
        btnExpDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExpDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnExpDoc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        
        if (txtFuncaoObjetivo.getText().isEmpty() || txtMatrixRestricoes.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(rootPane, "Os campos \"Função Objetivo\" e \"Matriz de Restrições\" não podem ser vazios!", "Aviso!", JOptionPane.INFORMATION_MESSAGE);
            
        } else {
        
            int nConstrs = 0;
            int nVars = 0;
            String fType = cbFType.getSelectedItem().toString();

            String fo = txtFuncaoObjetivo.getText();
            String [] zStr = fo.split(" ");
            nVars = zStr.length;
            
            Fraction[] z = new Fraction[zStr.length];

            for (int i = 0; i < zStr.length; i++) {
                z[i] = createFraction(zStr[i]);
            }

            String constrs[] = txtMatrixRestricoes.getText().split("\n");
            nConstrs = constrs.length;
//            System.out.println("nConstraints: " + nConstrs);
            Fraction [][]A = new Fraction[nConstrs][nVars];
            Fraction[] b = new Fraction[nConstrs];
            String[] relations = new String[nConstrs];

            for (int i = 0; i < nConstrs; i++) {
                //System.out.println(constrs[i]);
                String c[] = constrs[i].split(" ");
                if ( nVars != c.length - 2 ) {
                    String msg = "A matriz de restrições foi preenchida incorretamente.\nLembre-se. Seu sistema tem " +
                            nVars + " variáveis. Cada restrição deve conter " + nVars + " variáveis.\nVerifique também se você pôs a relação na inequação (<= ou >=, por exemplo)."
                            + "\nA equação conter todos os dados separados por espaço, por exemplo: "
                            + "\n4 3 2 3 5 <= 49";
                    JOptionPane.showMessageDialog(rootPane, msg , "Aviso!", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                
                for (int j = 0; j < c.length; j++) {
                    if (c[j].compareTo(">=") == 0 || c[j].compareTo("<=") == 0) {
                        relations[i] = c[j];
                    } else if (j == c.length - 1) {
                        b[i] = createFraction(c[j]);
                    } else {
                        A[i][j] = createFraction(c[j]);
                    }
                }
            }
//            for (int i = 0; i < relations.length; i++) {
//                String relation = relations[i];
//                System.out.println(relation);
//            }
//            System.out.println("Teste");
//            System.out.println("nVars: " + nVars);
//            System.out.println("nConsts: " + nConstrs);
//            
//            System.out.println(fType);
//            
//            for (int i = 0; i < z.length; i++) {
//                System.out.print(z[i] + " ");
//            }
//            System.out.println("");
//            
//            for (int i = 0; i < A.length; i++) {
//                for (int j = 0; j < A[0].length; j++) {
//                    System.out.print(A[i][j] + " ");
//                }
//                System.out.println("");
//            }
//            System.out.println("");
//            
//            for (int i = 0; i < relations.length; i++) {
//                System.out.println(relations[i] + " ");
//                
//            }
//            System.out.println("");
//            
//            for (int i = 0; i < b.length; i++) {
//                System.out.print(b[i] + " ");                
//            }
//            System.out.println("");
            
            Simplex s = new Simplex(fType, z, A, relations, b, nConstrs, nVars);
            s.solve();
//            File workingDirectory = new File(System.getProperty("user.home") + File.separator + "Desktop");
            File path = new File(System.getProperty("user.home") + File.separator + "Simplexius");
            br.com.simplexius.tools.Utils.exportToPDF("tableux", s.getLatexCode(), path);
            
            //txtMatrixRestricoes.setText(s.getLatexCode());
        }
        
        /*System.out.print("Z = ");
        for (int i = 0; i < nVars; i++) {
            System.out.print(z[i] +" ");
        }
        System.out.println("\nA = ");
        
        for (int i = 0; i < A.length; i++) {
            for (int j = 0; j < A[0].length; j++) {
                System.out.print(A[i][j] + " ");
            }
            System.out.println();
        }
        
        System.out.println("");
        for (int i = 0; i < relations.length; i++) {
            System.out.print(relations[i] + " ");
        }
        System.out.println("");
        
        for (int i = 0; i < b.length; i++) {
            System.out.print(b[i] + " ");
        }
        System.out.println("");*/
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtMatrixRestricoes.setText("");
        txtFuncaoObjetivo.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PrincipalPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PrincipalPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PrincipalPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PrincipalPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        // set system properties here that affect Quaqua
        // for example the default layout policy for tabbed
        // panes:
//        System.setProperty("Quaqua.tabLayoutPolicy","wrap");
        
        try {
            //UIManager.setLookAndFeel("com.seaglasslookandfeel.SeaGlassLookAndFeel");
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(PrincipalPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalPainel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnExpDoc;
    private javax.swing.JButton btnExpPDF;
    private javax.swing.JButton btnExpTex;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbFType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtFuncaoObjetivo;
    private javax.swing.JTextArea txtMatrixRestricoes;
    // End of variables declaration//GEN-END:variables

    private Fraction createFraction(String str) {
        Fraction f = null;
        
        if (!str.contains("/")) {
            f = new Fraction(str);
        } else {
            String frac[] = str.split("/");
            if (frac.length != 2) return null;//create problema with entrada
            f = new Fraction(frac[0], frac[1]);
        }
        
        return f;
    }
}
